require("ts.remap")
require("ts.set")
require("ts.load_lazy")
require("ts.kickstart_configs")
require("ts.diffview")
require("ts.fugitive")
require("ts.harpoon")
require("ts.lsp")
require("ts.trouble")
require("ts.undotree")
require("ts.ng")
require("ts.nx")

